name: clone仓库

on:
  push:
    branches:
      - master  # 或者你想要触发工作流的分支名
    schedule:
      - cron: '0 */1 * * *'  # 每1小时运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 克隆HyperDbg仓库
        run: git clone --recursive -b dev https://github.com/HyperDbg/HyperDbg.git
      - name: 安装zstd
        run: brew install zstd
      - name: 打包HyperDbg项目
        run: tar --zstd -cvf HyperDbg.tar.zst HyperDbg

      - name: 发布到GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: HyperDbg-dev-branch
          tag_name: latest
          files: HyperDbg.tar.zst
          body: |
            HyperDbg dev 分支克隆包
            更新时间: ${{ github.event.head_commit.timestamp }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
