name: clone仓库

on:
  push:
    branches:
      - master  # 或者你想要触发工作流的分支名
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 克隆unison仓库
        run: git clone --recursive https://github.com/richardwilkes/unison.git
      - name: 打包unison项目
        run: tar -czvf unison.tar.gz unison

      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      # manjaro linux
      # gioui提示vulkan构建约束被排除的原因是没有安装gcc，termux可以试试是不是这个原因
      # sudo pacman -S pkg-config vulkan-headers gcc clang cmake
      # yay -S android-sdk-build-tools  android-sdk-platform-tools
      # yay -S android-platform
      # go env -w GOPROXY=https://goproxy.cn,direct
      # go run 需要sudo

      - name: Install C library dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Run tests
        run: go test .


      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: unison-tar-gz
          path: unison.tar.gz
