name: clone仓库

on:
  push:
    branches:
      - master  # 或者你想要触发工作流的分支名
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 克隆sointu仓库
        run: git clone --recursive https://github.com/vsariola/sointu.git
      - name: 打包sointu项目
        run: zip -r sointu.zip sointu

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: sointu-zip
          path: sointu.zip
