name: clone仓库

on:
  push:
    branches:
      - master  # 或者你想要触发工作流的分支名
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 克隆unison仓库
        run: git clone --recursive https://github.com/richardwilkes/unison.git
      - name: 打包unison项目
        run: tar -czvf unison.tar.gz unison

      - name: Run tests
        run: go test .

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: unison-tar-gz
          path: unison.tar.gz
